### PR TITLE
Include branch coverage in submission too

### PR DESCRIPTION
**Pull request by muggenhor**
This adds the branch coverage that LCOV extracts to the JSON submitted to coveralls. This should provide branch coverage in your coveralls output.

### CODE REVIEW

**Comment by okkez** [comment]
Could you show me sample output before and after on coveralls.io?

**Comment by muggenhor** [comment]
Just before: https://coveralls.io/jobs/28800222
First build using this change: https://coveralls.io/jobs/28804861

Note the difference in the "run details" section. Without this change it only mentions "X hits per line" and "X of Y relevant lines covered". Using this change it also mentions "X of Y branches covered".

**Comment by okkez** [comment]
Wow! Cool! I will merge this PR and release new version as soon as possible.

**Comment by okkez** [comment]
Relased v1.5.0. Thanks!

**Pull request merged**
